// ESLint configuration for Svelte 5 + TypeScript
// Generated by claudeCodeSetup
import js from '@eslint/js';
import ts from 'typescript-eslint';
import svelte from 'eslint-plugin-svelte';
import globals from 'globals';
import svelteConfig from './svelte.config.js';

export default ts.config(
	js.configs.recommended,
	...ts.configs.recommended,
	...svelte.configs.recommended,
	{
		languageOptions: {
			globals: {
				...globals.browser,
				...globals.node
			},
			parserOptions: {
				projectService: true,
				extraFileExtensions: ['.svelte'],
				svelteConfig
			}
		}
	},
	{
		files: ['**/*.svelte', '**/*.svelte.ts', '**/*.svelte.js'],
		languageOptions: {
			parserOptions: {
				parser: ts.parser,
				svelteConfig,
				svelteFeatures: {
					runes: true // Enable Svelte 5 runes ($state, $derived, etc.)
				}
			}
		},
		rules: {
			// Disable no-navigation-without-resolve for internal routes
			// SvelteKit's internal routes don't need resolve() - it's mainly for assets
			'svelte/no-navigation-without-resolve': 'off',
			// Allow 'any' types in template components for flexibility
			// These components are designed to work with various data types
			'@typescript-eslint/no-explicit-any': 'off'
		}
	},
	{
		// Template *components* are intentionally flexible with `any` (see the
		// .svelte override above). Plain .ts files — server utilities, shared
		// types — should keep type safety honest, so surface `any` as a warning
		// rather than silencing it outright. Warnings don't fail CI but make new
		// `any` in the data/type layer visible in review.
		files: ['**/*.ts', '**/*.tsx'],
		ignores: ['**/*.svelte.ts'],
		rules: {
			'@typescript-eslint/no-explicit-any': 'warn'
		}
	},
	{
		// Disable type-aware linting for config files
		files: ['**/*.config.js', '**/*.config.ts'],
		...ts.configs.disableTypeChecked
	},
	{
		ignores: [
			'build/',
			'.svelte-kit/',
			'dist/',
			'.vercel/',
			'.claude/plans/',
			'node_modules/'
		]
	}
);
